### ISSUE TITLE
Fast extraction of a string as bytestring from a cursor

### ISSUE THREAD

**Issue by gbaz** [haskell-works/hw-json#121]
Suppose I have a cursor, and i know it is at a string, and I would like to get the bytestring representing the value of that string out of the cursor as efficiently as possible. How would I do so? Passing via LightJson, PartialValue, or Value all force there to be a String created. Meanwhile, JsonPartialIndex and JsonIndex are internal and seem to give the whole remainder. Is there no nice in-between thing available?

**Comment by newhoggy** [comment]
That's a good point.  Let me work on that.

**Comment by newhoggy** [comment]
At some point I would like to switch to use backpack because there may be more versions of `makeCursor` for fit for different use cases and an application will typically only want to choose one.

**Comment by gbaz** [comment]
in that case, "load" probably shouldn't use slow: https://github.com/haskell-works/hw-json/blob/master/src/HaskellWorks/Data/Json/Backend/Standard/Load/Cursor.hs

**Comment by gbaz** [comment]
vis a vis backpack, couldn't you equally well just make the cursor type abstract for the most part?

**Comment by newhoggy** [comment]
How do you mean?

**Comment by newhoggy** [comment]
I'll fix the load too.

**Comment by gbaz** [comment]
I just mean suppose you wrapped all your cursors in an abstract newtype that hid the various bits in terms of internal implementation. They all have the same external api, i'm not sure what is gained from needing to pick one via backpack...

**Comment by newhoggy** [comment]
Does that introduce an indirection with a performance penalty?

**Comment by newhoggy** [comment]
The other reason I'd like to use backpack is to avoid having to compile multiple versions of a thing that are never used.

**Comment by newhoggy** [comment]
And a bit of sanity so I don't accidentally use the wrong one like I just did.  I can't use the wrong version by accidentally if it was never in my package dependencies 😂

**Comment by newhoggy** [comment]
BTW, what did you mean when you said "get the bytestring representing the value of that string"

Did you want `"hello"` to be `"hello" :: ByteString` or `"\"hello\"" :: ByteString?

**Comment by gbaz** [comment]
The former would be better, but I'm not sweating it either way.

**Comment by newhoggy** [comment]
After re-familiarising myself with the code,`JsonIndex` is the closest to what you want, but it is correct that this indeed does give you the remainder.

**Comment by newhoggy** [comment]
What you really need is in the unfinished `Simple` Backend.

The `Simple` Backend would be able to give you the ability to get a slice of the original document as a `ByteString` that contains only the undecoded string and whatever whitespace is either side of it.

All the cursor functionality as well as very fast SIMD support for building the index.

Unfortunately there is no code to expose it as a nice API.

**Comment by newhoggy** [comment]
Both backends are described in the paper: http://www.di.unipi.it/~ottavian/files/semi_index_cikm.pdf

This is the standard backend:

![image](https://user-images.githubusercontent.com/63014/59973437-4d639f00-95e3-11e9-8743-dc81bc4b2d5d.png)

This is the `Simple` backend:

![image](https://user-images.githubusercontent.com/63014/59973440-56ed0700-95e3-11e9-8f89-9ebc13038e64.png)

Although the paper does not use the words standard or simple.

**Comment by newhoggy** [comment]
MankyKitty was asking for something similar too.  Maybe worth having a chat with him.

**Comment by gbaz** [comment]
I mean.. this is the hacky thing I have:

```
fastStringExtract :: Cursor -> Maybe BS.ByteString
fastStringExtract k =
  let p   = Json.lastPositionOf (Json.select1 (Json.interests k) (Json.rank1 (Json.balancedParens k) (Json.cursorRank k)))

  in if Json.isQuotDbl (BS.index (Json.cursorText k) (fromIntegral p))
          then Just $ BS.drop (fromIntegral $ p + 1) (Json.cursorText k)
          else Nothing

```

**Comment by newhoggy** [comment]
Closing this issue.  Re-open if there are any further problems.
