### ISSUE TITLE
Documentation: slow vs fast?

### ISSUE THREAD

**Issue by gbaz** [haskell-works/hw-json#122]
When do I use HaskellWorks.Data.Json.Backend.Standard.Fast vs. HaskellWorks.Data.Json.Backend.Standard.Slow? The documentation doesn't seem to help here...

**Comment by newhoggy** [comment]
`Slow` is a reference implementation for testing purposes.  I should move it into an `Internal` module so it isn't accidentally used.  Thanks!

**Comment by gbaz** [comment]
in that case, "load" probably shouldn't use slow: https://github.com/haskell-works/hw-json/blob/master/src/HaskellWorks/Data/Json/Backend/Standard/Load/Cursor.hs

**Comment by newhoggy** [comment]
This should be resolved in the next release.
