### ISSUE TITLE
Update Readme?

### ISSUE THREAD

**Issue by ocramz** [haskell-works/hw-json#181]
It seems like the library has evolved past the examples in the README, e.g. the modules

HaskellWorks.Data.Json.Standard.Cursor.Fast 
HaskellWorks.Data.TreeCursor  

don't exist anymore.

**Comment by newhoggy** [comment]
Thanks for the ticket.  I'll look at it shortly.

**Comment by newhoggy** [comment]
I've copied the examples into haskell files and compiled them and they work:

https://github.com/haskell-works/hw-json/pull/182

This indicates that the examples in the README are correct, but that the documentation is incomplete for not mentioning the additional dependencies necessary for running the examples.

I will update the README accordingly.

**Comment by newhoggy** [comment]
I've merged this pull request https://github.com/haskell-works/hw-json/pull/183

**Comment by ocramz** [comment]
Thank you for looking into this so quickly!
