### ISSUE TITLE
parseJsonString converts unicode hex codes wrong

### ISSUE THREAD

**Issue by gbaz** [haskell-works/hw-json#204]
```
ABC.parse HW.parseJsonString "\"qe-admin\\u2019s Mac\""
Done "" "qe-admin*** Exception: Prelude.chr: bad argument: 33554697

```

Whoops!

The offending line is 

https://github.com/haskell-works/hw-json/blob/f1efb1f103f352dc80942faf6a889ff870a2a2ac/src/HaskellWorks/Data/Json/Internal/Value.hs#L61

Those values are all doubled. They should be

`return $ chr $ a `shift` 12 .|. b `shift` 8 .|. c `shift` 4 .|. d`

However that's still not great, because `chr` is partial, which throws the exception we get, and its probably fine if the math is right (the argument to chr will then be in range) but it might be better to be explicitly safe about bounds as well.

**Comment by newhoggy** [comment]
Unfortunately I have trouble maintaining this library because I own an M1 Macbook now and don't have a suitable Intel machine this test this on.

**Comment by newhoggy** [comment]
Can you submit a PR that patches this up?

**Comment by gbaz** [comment]
done.
